version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    
  blockchain:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command: ["--host", "0.0.0.0"] 